version: "3"
services:
  # api:
  #   build: .
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - .:/app/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: technoblade
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - 3306:3306
